---
  title: "ENSO Impacts on Maize Agriculture in the Southwestern United States"
author: "Andrew Gillreath-Brown"
date: "`r format(Sys.time(), '%d %B %Y')`"
html_document:
  toc: yes
toc_depth: 2
toc_float: yes
number_sections: no
code_folding: hide
output:
  html_document:
  df_print: paged
mainfont: Calibri
editor_options:
  chunk_output_type: console
keep_md: yes
---
  
```{r setup, include = FALSE, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE)

# devtools::install()
# devtools::load_all()
#devtools::install_github("zeehio/facetscales")
library(ENSOMaizeImpacts)
require(ggh4x)
# 
# rcarbon_output <-
#   rcarbon::calibrate(x = c(2137, 1938, 1878), # normalized age
#                      errors = c(20, 19, 19), # one sigma error
#                      ids = c("AA-111725", "AA-110821", "AA-110819")) # unique ID for each 


 out <-  rcarbon::calibrate(x = c(2040), # normalized age
                     errors = c(13), # one sigma error
                     #calCurves = "intcal13",
                     ids = c("AA-89374")) # unique ID for each
summary(out)

# calib_curve <- read.csv("/Users/andrew/Downloads/3Col_intcal04.csv", header = F) %>% 
#   type.convert(as.is=TRUE) %>% 
#   arrange(V2) %>% 
#   complete(V2 = min(V2):max(V2)) %>% 
#   fill(V1, V3) %>% 
#   select(V1, V2, V3)


```

# Load the final reconstruction data.

```{r load_data, message = FALSE, warning = FALSE, results = 'hide'}

# Load the temperature anomaly reconstruction from paleoMAT.
temp_anom <- readr::read_csv("https://raw.githubusercontent.com/Archaeo-Programmer/paleoMAT/master/vignettes/tables/supp_table_s2.csv") %>% 
  dplyr::rename(year = 1, anom = 2, ci = 3, se = 4)

# Get calibrated maize database, extract GDD from the WorldClim dataset, then add back to the calibrated database.
# MDB_full_cal <- readr::read_csv("../Paper 2/Maize_Database_Calibrated.csv") %>% 
#   filter(str_detect(Country, "^Mexico") | str_detect(State_prov, "Arizona|Mexico|Utah|Colorado"))
# 
# readr::write_csv(MDB_full_cal, "../Paper 2/Maize_Database_Calibrated_SW_ONLY.csv")

MDB_full_cal <- readr::read_csv("../Paper 2/Maize_Database_Calibrated_SW_ONLY.csv", col_types = readr::cols())

MDB_full_cal <-  MDB_full_cal %>% 
  sf::st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  dplyr::select(Lab_code) %>%
  extract_GDD() %>% 
  dplyr::left_join(., MDB_full_cal, by = "Lab_code")
ok <- MDB_full_cal
#write.csv(MDB_full_cal, "MDB_full_cal_with_GDD.csv", row.names = F)
#MDB_full_cal <- read.csv("MDB_full_cal_with_GDD.csv", stringsAsFactors = FALSE)

#MDB_full_cal <- ok

# MDB_full_cal <- ok %>% 
#   dplyr::filter(Type == "MacroSample")

# Extract GDD for each location.
# MDB_full_cal <- ok %>%
#   dplyr::filter(Type == "MacroSample") %>%
#   dplyr::select(-gdd)
# 
# MDB_full_cal <-
#   raster::extract(
#     x =  global_gdd,
#     y = MDB_full_cal %>%
#       dplyr::select(Longitude, Latitude) %>%
#       dplyr::mutate(dplyr::across(everything(), ~ as.numeric(.x))),
#     df = TRUE
#   ) %>%
#   dplyr::select(gdd = 2) %>%
#   dplyr::bind_cols(MDB_full_cal, .)

# p3k14c_dates <- readr::read_csv("/Users/andrew/Downloads/p3k14c_raw.csv", col_types = readr::cols()) %>% 
#   dplyr::filter(Source == "CARD" & Country %in% c("USA", "Mexico")) %>% 
#   dplyr::select(LabID, Long, Lat)
# 
# 
# ok2 <- p3k14c::p3k14c_data %>% 
#   dplyr::filter(Province %in% c("Utah", "Arizona", "New Mexico", "Nevada", "Colorado") | Country == "Mexico") %>% 
#   dplyr::filter(str_detect(Taxa, "(?i)Zea mays|Maize|Zea maize")) %>% 
#   dplyr::select(-c(Long, Lat)) %>% 
#   dplyr::left_join(., p3k14c_dates, by = "LabID")


ok3 <-
  readr::read_csv("../Paper 2/Maize_Database_Calibrated_SW_ONLY.csv",
                  col_types = readr::cols()) %>%
  dplyr::left_join(.,
                   p3k14c::p3k14c_data %>% dplyr::select(LabID, Age, Error),
                   by = c("Lab_code" = "LabID")) %>%
  dplyr::select(1:5,
                Conventional_14C_age_BP,
                Age,
                plus_minus_1_sigma_yrs,
                Error) %>%
  filter(Country == "United States") %>% 
  filter(!is.na(Age)) %>% 
    dplyr::left_join(.,
                   p3k14c::p3k14c_data %>% dplyr::filter(str_detect(Taxa, "(?i)Zea may|Maize|Zea maize")) %>% dplyr::select(LabID, Age, Error),
                   by = c("Lab_code" = "LabID")) %>%
    dplyr::select(1:5,
                Conventional_14C_age_BP,
                Age,
                plus_minus_1_sigma_yrs,
                Error) 
  dplyr::mutate(
    Conventional_14C_age_BP = ifelse(!is.na(Age), Age, Conventional_14C_age_BP),
    plus_minus_1_sigma_yrs = ifelse(!is.na(Error), Age, Error)
  )
                                      

```


```{r Figure_1, fig.cap="Figure.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

# Create a bounding box for limits of this study
bb <-
  c(
    "xmin" = -112.81446,
    "xmax" = -105.52416,
    "ymin" = 32.65757,
    "ymax" = 38.089
  ) %>%
  sf::st_bbox() %>%
  sf::st_as_sfc() %>%
  sf::st_as_sf(crs = 4326) %>%
  sf::st_transform(crs = 4326)

usa <-
  sf::st_as_sf(maps::map("state", fill = TRUE, plot = FALSE)) %>%
  sf::st_transform(., crs = 4326) %>% 
  dplyr::filter(ID %in% c("colorado", "utah", "arizona", "new mexico"))

paleomat_extent <- 
  ggplot2::ggplot() +
  theme_bw() +
  scale_x_continuous(breaks = seq(-115, -103, 2.0),
                     limits = c(-115, -103.2)) +
  scale_y_continuous(breaks = seq(31, 39, 2.0),
                     limits = c(31.25, 39)) +
  geom_sf(
    data = usa,
    color = "#2b2b2b",
    fill = "transparent",
    size = 0.25
  ) +
  geom_sf(
    data = bb,
    size = 0.75,
    fill = NA,
    aes(colour = "slategrey",
        linetype = "dashed"),
    show.legend = "line",
    inherit.aes = FALSE
  ) +
  scale_color_manual(
    values = c("slategrey" = "slategrey"),
    labels = c("Gillreath-Brown et al. 2022 \n Study Area"),
    name = "Data Extent"
  ) +
  scale_linetype_manual(
    values = c("dashed" = "dashed"),
    labels = c("Gillreath-Brown et al. 2022 \n Study Area"),
    name = "Data Extent"
  ) +
  labs(colour = "") +
  annotate(
    "text",
    x = -109.2,
    y = 37.5,
    label = "UTAH",
    size = 4,
    fontface = 2,
    hjust = 1.0
  ) +
  annotate(
    "text",
    x = -108.90,
    y = 37.5,
    label = "COLORADO",
    size = 4,
    fontface = 2,
    hjust = 0
  ) +
  annotate(
    "text",
    x = -109.2,
    y = 36.3,
    label = "ARIZONA",
    size = 4,
    fontface = 2,
    hjust = 1
  ) +
  annotate(
    "text",
    x = -108.90,
    y = 36.3,
    label = "NEW MEXICO",
    size = 4,
    fontface = 2,
    hjust = 0
  ) +
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    legend.text=element_text(size=12),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_blank(),
    axis.text.x = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_rect(fill = "transparent",
                                    colour = NA_character_),
    plot.background = element_rect(fill = "transparent",
                                   colour = NA_character_), # necessary to avoid drawing plot outline
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.box.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
    legend.box.margin=margin(-10,-10,-10,-20)
  )


anom_plot <- temp_anom %>%
  ggplot2::ggplot(aes(x = year, y = anom)) +
  geom_ribbon(aes(ymax = anom + se, ymin = anom - se), alpha = 0.2) +
  geom_line(size = 2, colour = "cornflowerblue") +
  geom_hline(
    yintercept = 0,
    linetype = 'dashed',
    color = c('darkslategray')
  ) +
  scale_x_continuous(
    limits = c(-3000, 2100),
    breaks = seq(-3000, 2000, 500),
    minor_breaks = seq(-2900, 2000, by = 100),
    guide = "axis_minor",
    labels = c(seq(-3000, -500, 500), 1, seq(500, 2000, 500))
  ) +
  scale_y_continuous(
    limits = c(-2.5, 2.5),
    breaks = seq(-2.5, 2.5, 0.5),
    minor_breaks = seq(-2.5, 2.5, by = 0.25),
    guide = "axis_minor"
  ) +
  theme_bw() +
  xlab("Years BC/AD") +
  ylab("Temperature Anomaly (°C)") +
  theme(
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )


plot.with.inset <-
  cowplot::ggdraw() +
  cowplot::draw_plot(anom_plot) +
  cowplot::draw_plot(paleomat_extent, x = 0.04, y = .638, width = .51, height = .34)


ggplot2::ggsave(filename = "vignettes/figures/Figure_1.png", 
       plot = plot.with.inset,
       width = 15.51, height = 10.32, dpi = 600)


```

```{r Figure_2, fig.cap="Figure.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

temp_anom_standard <- readr::read_csv("https://raw.githubusercontent.com/Archaeo-Programmer/paleoMAT/master/vignettes/tables/supp_table_s2.csv") %>%
  dplyr::mutate(Year = as.integer(Year)) %>%
  dplyr::filter(Year >= 133 & Year <= 1900) %>%
  dplyr::mutate(Series = "This study") %>%
  dplyr::select(year = Year, anom = 2, Series)

Moberg_standard <- paleomat::moberg_2005 %>%
  dplyr::mutate(Series = "Moberg et al. 2005") %>%
  dplyr::select(year = date, anom = LF, Series) %>%
  dplyr::filter(year >= 133 & year <= 1900)

Moberg_paleomat <-
  dplyr::bind_rows(temp_anom_standard, Moberg_standard)

# Moberg LF and paleomat
Moberg_paleomat_fig <- Moberg_paleomat %>%
  dplyr::group_by(Series) %>%
  dplyr::mutate(update = (anom - mean(anom)) / sd(anom)) %>%
  ggplot2::ggplot(aes(x = year, y = update, colour = Series)) +
  geom_hline(
    yintercept = 0,
    color = "darkgrey",
    lty = 2,
    lwd = 1.25
  ) +
  geom_line(size = 2.0) +
  scale_color_manual(values = c("#A60F2D", "cornflowerblue")) +
  xlab("Years AD") +
  ylab("Standardized Temperature Values (Z-Scores)") +
  scale_x_continuous(
    limits = c(0, 2000),
    breaks = seq(0, 2000, 200),
    minor_breaks = seq(0, 2000, by = 100),
    guide = "axis_minor",
    labels = c(1, seq(200, 2000, 200))
  ) +
  scale_y_continuous(breaks = seq(-2, 3, 0.5)) +
  theme_bw() +
  guides(color = guide_legend(override.aes = list(fill = NA), direction = "horizontal")) +
  theme(
    legend.text = element_text(size = 19, family = "Helvetica"),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.margin = margin(t = -14),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

ggplot2::ggsave(Moberg_paleomat_fig, filename = "vignettes/figures/Figure_2.png", width = 17.25, height = 11.5, dpi = 600)
  
```

```{r Figure_3, fig.cap="Figure.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

MDB_full_cal <- ok %>%
  dplyr::filter(Type == "MacroSample")

# Determine which columns have "NA to NA" present (mostly just the 'sigma' date columns), so that we can replace with NA.
NA_select <- colSums("NA to NA" == MDB_full_cal %>% dplyr::select(-geometry), na.rm = TRUE) > 0
NA_select <- names(NA_select[NA_select == TRUE & !is.na(NA_select)])

# Find minimum 2 sigma for each row.
# Change all text that says "NA to NA" from the rcarbon output to a regular NA.
MDB_full_cal <- MDB_full_cal %>%
  dplyr::mutate(dplyr::across(dplyr::all_of(NA_select), ~ stringr::str_replace_all(.x, "NA to NA", NA_character_))) %>% 
  dplyr::filter(Country == "Mexico" | State_prov %in% c("Arizona", "New Mexico", "Utah", "Colorado"))

# subset the dataframe to only have the 2 sigma data and the unique lab code.
MDB_full_cal_min <- MDB_full_cal %>%
  dplyr::select(1, starts_with("TwoSigma")) %>%
  tidyr::pivot_longer(-Lab_code) %>%
  dplyr::filter(!is.na(value)) %>%
  dplyr::group_by(Lab_code) %>%
  dplyr::slice(dplyr::n()) %>%
  dplyr::select(Lab_code, MinBP = value) %>%
  # Extract the minimum year from the range of the 2 sigma date.
  dplyr::mutate(MinBP = as.numeric(stringr::str_extract(MinBP, "(?i)(?<=to\\D)\\d+"))) %>%
  # Add this data back to the large dataframe.
  dplyr::left_join(MDB_full_cal, ., by = "Lab_code") %>%
  # Reorder so that the Min years are located in the column next to medianBP.
  dplyr::relocate(MinBP, .after = MedianBP) %>%
  # dplyr::group_by(State_prov) %>%
  # dplyr::slice_max(MinBP) %>%
  dplyr::mutate(date = rcarbon::BPtoBCAD(MinBP)) %>%
  dplyr::select(Lab_code, Site_name, date, Latitude, gdd, everything())

# Linear Model and Stats
lm1 <- lm(Latitude ~ date, data = MDB_full_cal_min)
setNames(
  c(
    lm1$coefficients[["date"]],
    summary(lm1)$r.squared,
    summary(lm1)$coefficients[2, 4]
  ),
  c("slope", "r2", "pvalue")
)

# Plot using a linear model.
figure3 <-
  MDB_full_cal_min %>%
  dplyr::mutate(State_prov = as.factor(State_prov)) %>%
  dplyr::arrange(date) %>%
  dplyr::mutate(labels = paste0(
    stringr::str_replace(Site_name, " \\s*\\([^\\)]+\\)", ""),
    ", \n ",
    State_prov
  )) %>%
  ggplot(aes(x = date, y = Latitude)) +
  geom_point(size = 4, aes(shape = fct_rev(Country))) +
  scale_shape_manual(values = c(19, 15), name = "Country") +
  geom_smooth(
    aes(group = 1),
    method = 'lm',
    se = FALSE,
    linetype = 1,
    color = "black"
  ) +
  ggrepel::geom_label_repel(
    aes(label = labels),
    max.iter = 4500,
    cex = 6.7,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    force = 25,
    box.padding = 1
  ) +
  scale_x_continuous(
    breaks = seq(-4500, 1500, 500),
    minor_breaks = seq(-4500, 1500, 100),
    limits = c(-4500, 1500),
    guide = "axis_minor",
    labels = c(seq(-4500, -500, 500), 1, seq(500, 1500, 500))
  ) +
  scale_y_continuous(
    breaks = seq(10, 45, 5),
    minor_breaks = seq(10, 45, 1),
    limits = c(10, 45),
    guide = "axis_minor"
  ) +
  xlab("Years BC/AD") +
  ylab("Latitude") +
  # ggpubr::color_palette(palette = "jco") +
  theme_bw()  +
  guides(color = guide_legend(override.aes = list(fill = NA), direction = "horizontal")) +
  theme(
    legend.title = element_text(
      size = 19,
      family = "Helvetica",
      face = "bold"
    ),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(size = 18, colour = "black"),
    legend.margin = margin(t = -14),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 7,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 7,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

ggplot2::ggsave(figure3, filename = "vignettes/figures/Figure_3.png", width = 17.25, height = 11.5, dpi = 600)


# Using rayshader with GDD.
mtplot <- 
  MDB_full_cal_min %>%
  dplyr::left_join(., temp_anom, by = c("date" = "year")) %>%
  dplyr::mutate(State_prov = as.factor(State_prov)) %>%
  dplyr::arrange(date) %>%
  dplyr::mutate(labels = paste0(
    stringr::str_replace(Site_name, " \\s*\\([^\\)]+\\)", ""),
    ", \n ",
    State_prov
  )) %>%
  ggplot(aes(x = date, y = Latitude, color = anom)) +
  geom_point(size = 2) +
  scale_colour_gradientn(limits = c(0, 7000), colors = colorRampPalette(rev(RColorBrewer::brewer.pal(8, "RdBu")))(150)) +
  scale_x_continuous(
    breaks = c(seq(-4500,-500, 1000), 1, seq(500, 1500, 1000)),
    minor_breaks = c(seq(-4000,-1000, 1000), 1000),
    limits = c(-4500, 1500),
    guide = "axis_minor",
    labels = c(seq(-4500,-500, 1000), 1, seq(500, 1500, 1000))
  ) +
  scale_y_continuous(
    breaks = seq(10, 45, 5),
    minor_breaks = seq(10, 45, 1),
    limits = c(10, 45),
    guide = "axis_minor"
  ) +
  xlab("Years BC/AD") +
  ylab("Latitude") +
  labs(colour = "GDD") +
  theme_bw()  +
  theme(
    legend.title = element_text(
      size = 14,
      family = "Helvetica",
      face = "bold"
    ),
    legend.title.align = 1.0,
    legend.position = "right",
    legend.direction = "vertical",
    legend.text = element_text(size = 12, colour = "black"),
    legend.margin = margin(t = -14),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 12,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 14,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 7,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 14,
      family = "Helvetica",
      margin = margin(
        t = 7,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )


plot_gg(
  mtplot,
  width = 6.5,
  height = 4,
  multicore = TRUE,
  windowsize = c(1000, 1000),
  zoom = 0.77,
  phi = 50,
  theta = 35,
  sunangle = 225,
  soliddepth = -0.5,
  pointcontract = 0.7,
  scale = 200
)
render_snapshot(clear = TRUE, filename = "vignettes/figures/rayshader.png")



mtplot2 <- 
  MDB_full_cal_min %>%
  dplyr::filter(State_prov %in% c("Arizona", "New Mexico", "Utah", "Colorado")) %>% 
  dplyr::left_join(., temp_anom, by = c("date" = "year")) %>%
  dplyr::mutate(State_prov = as.factor(State_prov)) %>%
  dplyr::arrange(date) %>%
  dplyr::mutate(labels = paste0(
    stringr::str_replace(Site_name, " \\s*\\([^\\)]+\\)", ""),
    ", \n ",
    State_prov
  )) %>%
  ggplot(aes(x = date, y = Latitude, color = anom)) +
  geom_point(size = 2) +
  scale_colour_gradientn(limits = c(-2.0, 2.0), colors = colorRampPalette(rev(RColorBrewer::brewer.pal(8, "RdBu")))(150)) +
  scale_x_continuous(
    breaks = c(seq(-3000,-500, 500), 1, seq(500, 1500, 500)),
    minor_breaks = c(seq(-3000,-100, 100), seq(100,1400, 100)),
    limits = c(-3000, 1500),
    guide = "axis_minor",
    labels = c(seq(-3000,-500, 500), 1, seq(500, 1500, 500))
  ) +
  scale_y_continuous(
    breaks = seq(30, 42, 2),
    minor_breaks = seq(30, 42, 1),
    limits = c(30, 42),
    guide = "axis_minor"
  ) +
  xlab("Years BC/AD") +
  ylab("Latitude") +
  labs(colour = "Anomaly\n(°C)") +
  theme_bw()  +
  theme(
    legend.title = element_text(
      size = 13,
      family = "Helvetica",
      face = "bold"
    ),
    legend.title.align = 1.0,
    legend.position = "right",
    legend.direction = "vertical",
    legend.text = element_text(size = 11, colour = "black"),
    legend.margin = margin(t = -14),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 11,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 14,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 7,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 14,
      family = "Helvetica",
      margin = margin(
        t = 7,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )


plot_gg(
  mtplot2,
  width = 6.5,
  height = 4,
  multicore = TRUE,
  windowsize = c(1000, 1000),
  zoom = 0.77,
  phi = 50,
  theta = 35,
  sunangle = 225,
  soliddepth = -0.5,
  pointcontract = 0.7,
  scale = 200
)

render_snapshot(clear = TRUE, filename = "vignettes/figures/rayshader_Anom.png")


```


```{r Figure_4, fig.cap="Figure.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

MDB_full_cal <- ok %>%
  dplyr::filter(Type == "MacroSample")

# Determine which columns have "NA to NA" present (mostly just the 'sigma' date columns), so that we can replace with NA.
NA_select <-
  colSums("NA to NA" == MDB_full_cal %>% dplyr::select(-geometry), na.rm = TRUE) > 0
NA_select <- names(NA_select[NA_select == TRUE & !is.na(NA_select)])

# Find minimum 2 sigma for each row.
# Change all text that says "NA to NA" from the rcarbon output to a regular NA.
MDB_full_cal <- MDB_full_cal %>%
  dplyr::mutate(dplyr::across(
    dplyr::all_of(NA_select),
    ~ stringr::str_replace_all(.x, "NA to NA", NA_character_)
  )) %>%
  dplyr::filter(Country == "Mexico" |
                  State_prov %in% c("Arizona", "New Mexico", "Utah", "Colorado"))

# Subset the dataframe to only have the 2 sigma data and the unique lab code.
MDB_full_cal_min <- MDB_full_cal %>%
  dplyr::select(1, starts_with("TwoSigma")) %>%
  tidyr::pivot_longer(-Lab_code) %>%
  dplyr::filter(!is.na(value)) %>%
  dplyr::group_by(Lab_code) %>%
  dplyr::slice(n()) %>%
  dplyr::select(Lab_code, MinBP = value) %>%
  # Extract the minimum year from the range of the 2 sigma date.
  dplyr::mutate(MinBP = as.numeric(stringr::str_extract(MinBP, "(?i)(?<=to\\D)\\d+"))) %>%
  # Add this data back to the large dataframe.
  dplyr::left_join(MDB_full_cal, ., by = "Lab_code") %>%
  # Reorder so that the Min years are located in the column next to medianBP.
  dplyr::relocate(MinBP, .after = MedianBP) %>%
  # Create 100 year bins.
  dplyr::mutate(bin = cut(
    MinBP,
    breaks = seq(
      plyr::round_any(min(MinBP), 100, f = floor),
      plyr::round_any(max(MinBP), 100, f = ceiling),
      by = 100
    ),
    include.lowest = TRUE
  )) %>%
  dplyr::group_by(bin) %>%
  dplyr::slice_max(Latitude) %>%
  dplyr::slice_max(MinBP) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(desc(MinBP)) %>%
  dplyr::filter(Latitude == cummax(Latitude)) %>%
  dplyr::mutate(date = rcarbon::BPtoBCAD(MinBP)) %>%
  dplyr::select(Lab_code, Site_name, date, bin, gdd, everything()) %>%
  dplyr::filter(date <= 1500) %>%
  dplyr::group_by(Site_name) %>%
  dplyr::slice_min(date, with_ties = FALSE) %>%
  dplyr::ungroup()

# Linear Model and Stats
lm1 <- lm(Latitude ~ date, data = MDB_full_cal_min)
setNames(
  c(
    lm1$coefficients[["date"]],
    summary(lm1)$r.squared,
    summary(lm1)$coefficients[2, 4]
  ),
  c("slope", "r2", "pvalue")
)

# Plot using a linear model.
figure4 <-
  MDB_full_cal_min %>%
  dplyr::mutate(State_prov = fct_reorder(State_prov, date, .fun = 'min')) %>%
  dplyr::arrange(date) %>%
  dplyr::mutate(labels = stringr::str_replace(Site_name, " \\s*\\([^\\)]+\\)", "")) %>%
  ggplot(aes(x = date, y = Latitude)) +
  geom_point(size = 4, aes(color = State_prov, shape = State_prov)) +
  geom_smooth(
    aes(group = 1),
    method = 'lm',
    se = FALSE,
    linetype = 1,
    color = "black"
  ) +
  # stat_poly_eq(aes(label = paste(after_stat(eq.label),
  #                              after_stat(rr.label), sep = "*\", \"*"))) +
  ggrepel::geom_label_repel(
    aes(colour = State_prov, label = labels),
    max.iter = 4500,
    cex = 6.7,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    force = 25,
    box.padding = 1
  ) +
  scale_x_continuous(
    breaks = seq(-4500, 1500, 500),
    minor_breaks = seq(-4500, 1500, 100),
    limits = c(-4500, 1500),
    guide = "axis_minor",
    labels = c(seq(-4500,-500, 500), 1, seq(500, 1500, 500))
  ) +
  scale_y_continuous(
    breaks = seq(15, 45, 5),
    minor_breaks = seq(15, 45, 1),
    limits = c(15, 45),
    guide = "axis_minor"
  ) +
  xlab("Years BC/AD") +
  ylab("Latitude") +
  scale_shape_manual(
    values = c(3, 19, 15, 17, 9),
    name = "States",
    labels = c("Oxaca", "Arizona", "New Mexico", "Utah", "Colorado")
  ) +
  scale_color_manual(
    values = ggsci::pal_jco("default")(10)[c(1, 3, 2, 4, 6)],
    name = "States",
    labels = c("Oxaca", "Arizona", "New Mexico", "Utah", "Colorado")
  ) +
  theme_bw()  +
  theme(
    legend.position = "bottom",
    legend.title = element_text(
      size = 19,
      family = "Helvetica",
      face = "bold"
    ),
    legend.direction = "horizontal",
    legend.text = element_text(size = 18, colour = "black"),
    legend.margin = margin(t = -14),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 7,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 7,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

ggplot2::ggsave(
  figure4,
  filename = "vignettes/figures/Figure_4.png",
  width = 17.25,
  height = 11.5,
  dpi = 600
)

```


```{r Figure_5, fig.cap="Figure.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

MDB_full_cal <- ok %>%
  dplyr::filter(Type == "MacroSample")

# Determine which columns have "NA to NA" present (mostly just the 'sigma' date columns), so that we can replace with NA.
NA_select <-
  colSums("NA to NA" == MDB_full_cal %>% dplyr::select(-geometry), na.rm = TRUE) > 0
NA_select <- names(NA_select[NA_select == TRUE & !is.na(NA_select)])

# Find minimum 2 sigma for each row.
# Change all text that says "NA to NA" from the rcarbon output to a regular NA.
MDB_full_cal <- MDB_full_cal %>%
  dplyr::mutate(dplyr::across(
    dplyr::all_of(NA_select),
    ~ stringr::str_replace_all(.x, "NA to NA", NA_character_)
  )) %>%
  dplyr::filter(State_prov %in% c("Arizona", "New Mexico", "Utah", "Colorado"))

# subset the dataframe to only have the 2 sigma data and the unique lab code.
MDB_full_cal_min <- MDB_full_cal %>%
  dplyr::select(1, starts_with("TwoSigma")) %>%
  tidyr::pivot_longer(-Lab_code) %>%
  dplyr::filter(!is.na(value)) %>%
  dplyr::group_by(Lab_code) %>%
  dplyr::slice(n()) %>%
  dplyr::select(Lab_code, MinBP = value) %>%
  # Extract the minimum year from the range of the 2 sigma date.
  dplyr::mutate(MinBP = as.numeric(stringr::str_extract(MinBP, "(?i)(?<=to\\D)\\d+"))) %>%
  # Add this data back to the large dataframe.
  dplyr::left_join(MDB_full_cal, ., by = "Lab_code") %>%
  # Reorder so that the Min years are located in the column next to medianBP.
  dplyr::relocate(MinBP, .after = MedianBP) %>%
  # Create 100 year bins.
  dplyr::mutate(bin = cut(
    MinBP,
    breaks = seq(
      plyr::round_any(min(MinBP), 100, f = floor),
      plyr::round_any(max(MinBP), 100, f = ceiling),
      by = 100
    ),
    include.lowest = TRUE
  )) %>%
  dplyr::group_by(bin) %>%
  dplyr::slice_max(Latitude) %>%
  dplyr::slice_max(MinBP) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(desc(MinBP)) %>%
  dplyr::filter(Latitude == cummax(Latitude)) %>%
  dplyr::mutate(date = rcarbon::BPtoBCAD(MinBP)) %>%
  dplyr::select(Lab_code, Site_name, date, bin, gdd, everything()) %>%
  dplyr::filter(date <= 1500) %>%
  dplyr::group_by(Site_name) %>%
  dplyr::slice_min(date, with_ties = FALSE) %>%
  dplyr::ungroup()

# Linear Model and Stats
lm1 <- lm(Latitude ~ date, data = MDB_full_cal_min)
setNames(
  c(
    lm1$coefficients[["date"]],
    summary(lm1)$r.squared,
    summary(lm1)$coefficients[2, 4]
  ),
  c("slope", "r2", "pvalue")
)

# Plot using a linear model.
figure5 <-
  MDB_full_cal_min %>%
  dplyr::mutate(State_prov = fct_reorder(State_prov, date, .fun = 'min')) %>%
  dplyr::arrange(date) %>%
  dplyr::mutate(labels = stringr::str_replace(Site_name, " \\s*\\([^\\)]+\\)+$", "")) %>%
  ggplot(aes(x = date, y = Latitude)) +
  geom_point(size = 4, aes(color = State_prov, shape = State_prov)) +
  geom_smooth(
    aes(group = 1),
    method = 'lm',
    se = FALSE,
    linetype = 1,
    color = "black"
  ) +
  # stat_poly_eq(aes(label = paste(after_stat(eq.label),
  #                              after_stat(rr.label), sep = "*\", \"*"))) +
  ggrepel::geom_label_repel(
    aes(colour = State_prov, label = labels),
    max.iter = 4500,
    cex = 6.7,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    force = 25,
    box.padding = 1
  ) +
  scale_shape_manual(
    values = c(19, 15, 17, 9),
    name = "States",
    labels = c("Arizona", "New Mexico", "Utah", "Colorado")
  ) +
  scale_color_manual(
    values = ggsci::pal_jco("default")(10)[c(3, 2, 4, 6)],
    name = "States",
    labels = c("Arizona", "New Mexico", "Utah", "Colorado")
  ) +
  scale_x_continuous(
    breaks = seq(-4500, 1500, 500),
    minor_breaks = seq(-4500, 1500, 100),
    limits = c(-4500, 1500),
    guide = "axis_minor",
    labels = c(seq(-4500,-500, 500), 1, seq(500, 1500, 500))
  ) +
  scale_y_continuous(
    breaks = seq(30, 42, 2),
    minor_breaks = seq(30, 42, 1),
    limits = c(30, 42),
    guide = "axis_minor"
  ) +
  xlab("Years BC/AD") +
  ylab("Latitude") +
  theme_bw()  +
  theme(
    legend.position = "bottom",
    legend.title = element_text(
      size = 19,
      family = "Helvetica",
      face = "bold"
    ),
    legend.direction = "horizontal",
    legend.text = element_text(size = 18, colour = "black"),
    legend.margin = margin(t = -14),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 7,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 7,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

ggplot2::ggsave(
  figure5,
  filename = "vignettes/figures/Figure_5.png",
  width = 17.25,
  height = 11.5,
  dpi = 600
)

```


# Other Possible Figures
```{r GDD_SW_map}

# raster::crs(temp.raster) <-
#   "+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +ellps=GRS80 +datum=WGS84 +units=m +no_defs"
accum_GDD_annual_data <- raster::as.data.frame(accum_GDD_annual, xy = TRUE)
names(accum_GDD_annual_data) <- c("long", "lat", "GDD")
accum_GDD_annual_data_transformed <-
  usmap::usmap_transform(
    accum_GDD_annual_data,
    input_names = c("long", "lat"),
    output_names = c("x", "y")
  )

# usa_mexico_states2 <- usa_mexico_states %>% 
#   # MDB_full_cal_min is the data from Figure 3
#   dplyr::mutate(state_abbr = ifelse(state_name %in% c(MDB_full_cal_min$State_prov, "Mexico"), state_abbr, NA_character_))
usa_mexico_states2 <- usa_mexico_states %>% 
  # MDB_full_cal_min is the data from Figure 3
  dplyr::mutate(state_name = ifelse(state_name %in% c(MDB_full_cal_min$State_prov, "Mexico"), state_name, NA_character_))

america_dem <- elevatr::get_elev_raster(locations = usa_mexico_states, z = 10)

# Put elevation and temperature rasters in the same resolution.
ned_SW <- raster::projectRaster(america_dem, accum_GDD_annual, method = 'ngb')

ned_SW_crop <- raster::crop(ned_SW, usa_mexico_states)
#then mask out (i.e. assign NA) the values outside the polygon
ned_SW_mask <- raster::mask(ned_SW_crop, usa_mexico_states)

# Create a hillshade file.
slope <- raster::terrain(ned_SW_mask, opt='slope')
aspect <- raster::terrain(ned_SW_mask, opt='aspect')
hill <- raster::hillShade(slope, aspect,
                          angle = 40,
                          direction = 270)
hill_spdf <- as(hill, "SpatialPixelsDataFrame")
hill_spdf <- raster::as.data.frame(hill_spdf)
colnames(hill_spdf) <- c("value", "x", "y")
   
  
GDD_map <-
  ggplot2::ggplot() +
  ggplot2::geom_raster(
    data = hill_spdf,
    mapping = aes(x = x,
                  y = y,
                  alpha = value),
    na.rm = TRUE,
    inherit.aes = FALSE
  ) +
  # use the "alpha hack"
  scale_alpha(
    name = "",
    range = c(0.6, 0),
    na.value = 0,
    #limits = c(0,255),
    guide = FALSE
  )  +
  geom_raster(
    data = accum_GDD_annual_data_transformed,
    aes(x = long, y = lat, fill = GDD),
    alpha = 0.8,
    na.rm = TRUE
  ) +
  # scale_fill_gradientn(
  #   colors = grey.colors(
  #     10,
  #     start = 0.15,
  #     end = 0.9,
  #     rev = TRUE
  #   ),
  #   na.value = "transparent",
  #   name = "Annual GDDs"
  # ) +
  scale_fill_gradientn(colors = colorRampPalette(rev(RColorBrewer::brewer.pal(11, "RdBu")))(255),
                       na.value = "transparent",
                       name = "Annual GDDs") +
  coord_equal() +
  theme_map() +
  geom_sf(
    data = usa_mexico_states,
    color = "#2b2b2b",
    fill = "transparent",
    size = 0.4,
    inherit.aes = FALSE
  ) +
  ggrepel::geom_label_repel(
    data = usa_mexico_states2,
    aes(label = state_name, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0.4,
    force = 40.5,
    label.size = 0,
    size = 4.5
  ) +
  theme(
    #legend.key.width = unit(1.25, 'cm'),
    legend.position = c(.15, .2),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_blank(),
    axis.text.x = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    legend.text = element_text(size = 15, family = "Helvetica"),
    legend.title = element_text(
      size = 16,
      family = "Helvetica",
      face = "bold"
    )
  )

ggplot2::ggsave(GDD_map, 
                filename = "vignettes/figures/GDD_map2.png", 
       width = 15.43, height = 13.15, dpi = 600)

```




```{r process_maize_frontier, message = FALSE, warning = FALSE, results = 'hide'}

# Find minimum 2 sigma for each row.
# Change all text that says "NA to NA" from the rcarbon out put to a regular NA.
MDB_full_cal <- MDB_full_cal %>%
  dplyr::mutate_all(function(x) gsub("NA to NA", NA, x))
# subset the dataframe to only have the 2 sigma data and the unique lab code.
df1 <- MDB_full_cal %>% dplyr::select(1, 35:41)
#create an index that shows which cells are and are not NA.
ind <- !is.na(df1)
# Get the last sigma date that is True in each row (/the last non-NA value).
sigma_min <- tapply(df1[ind], row(df1)[ind], tail, 1)
#Bind back to lab_code. Need to fix these 2 lines of code, so that I never lose the unique identifier.
sigma_min <- cbind(df1$Lab_code, sigma_min)
#Update colnames.
colnames(sigma_min) <- c("Lab_code", "MinBP")
#Separating the text in each date box, so that I can extract the minimum year.
sigma_min <- sigma_min %>%
  as.data.frame() %>%
  tidyr::separate(MinBP, into = c("pre", "to", "MinBP")) %>%
  dplyr::select(-pre:-to)

# Add this data back to the large dataframe.
MDB_full_cal_min <- dplyr::left_join(MDB_full_cal, sigma_min, by = "Lab_code")
#Reorder so that the Min years are by medianBP.
MDB_full_cal_min <- MDB_full_cal_min %>% dplyr::relocate(MinBP, .after = MedianBP)


# Reorder the latitude to be in ascending order.
garb <- MDB_full_cal_min %>%
  dplyr::arrange(Latitude)

# Find index of the oldest date in maize data using the minimum BP year, then remove all rows above that date.
delrows <- which.max(garb$MinBP) - 1
garb <- garb %>%
  dplyr::slice(-1:-delrows)

# Get the actual year and latitude for the oldest maize sample.
starting_maize <- which.max(garb$MinBP)
garb$MinBP <- as.numeric(garb$MinBP)
garb$Latitude <- as.double(garb$Latitude)
starting_date <- garb[starting_maize, ] %>% .$MinBP
starting_lat <- garb[starting_maize, ] %>% .$Latitude

# Get the minimum latitude in the dataset.
#min_lat <- as.double(min(garb$Latitude))
# min_lat%%1
# Round down the minimum latitude (in order to create 1 degree latitude bins).
floor_lat <- floor(starting_lat)
# floor_lat <- format(round(floor_lat, 10), nsmall = 10)
# floor_lat <- as.numeric(floor_lat)


# Limit just to SW.
garb <- garb %>%
  filter(str_detect(Country, "^Mexico") | str_detect(State_prov, "Arizona|Mexico|Utah|Colorado"))

# Get the maximum latitude in the dataset.
max_lat <- as.double(max(garb$Latitude))
# Round up the maximum latitude (in order to create 1 degree latitude bins), but make it only go to 0.99999999.
ceiling_lat <- ceiling(max_lat) - 0.0000000001

noBins <- (ceiling_lat - floor_lat) + 0.0000000001

# Create new dataframe that has the northern frontier of maize through time. Pick a site that is farther north than the previous site and younger.
# LOOP: Set up a loop by first determining how many bins there are. For example, if I do a bin size of 1 degree for latitude, and if the latitude range
# is from 15 to 20, then I would have 5 bins. That would give me how many times I need to loop through.
# Then, I would find the starting point for the first record, whether that is starting with the absolute oldest date or starting at the lowest latitude with the oldest date.
# Once i have a starting point, then I want to loop through each bin (e.g., 15-16, 16-17, etc.) and find the oldest date, but it must be younger than the previous selection.

# Create bins.
# Find cutoffs for the latitude bins in the dataset.
cutOffs <- c((floor_lat):(ceiling_lat))

# Convert to make sure columns are numeric then create the actual bins (as factors).
garb$bins <- cut(as.numeric(garb$Latitude), breaks=cutOffs)
garb$binsNo <- cut(as.numeric(garb$Latitude), breaks=cutOffs, labels = FALSE)

#test <- garb %>% group_by(bins) %>% top_n(1, MinBP)
unique_bins <- unique(garb$bins)

garb1 <- garb


for (i in 1:length(unique_bins)){
  
  if (i == 1){
    garb1 <- garb1 %>%
      dplyr::group_by(bins) %>%
      dplyr::mutate(maxage = ifelse(bins == unique_bins[i], max(MinBP), NA))
    
    max_agecurrent <- max(garb1$MinBP)
  } else {
    max_ageprev <- max_agecurrent
    # garb1 %>%
    #   ungroup() %>%
    #   dplyr::filter(bins == unique_bins[i-1]) %>%
    #   dplyr::filter(MinBP < max_ageprev) %>%
    #   dplyr::select(MinBP) %>%
    #   max(.)
    
    subset <- garb1 %>%
      dplyr::ungroup() %>%
      dplyr::filter(bins == unique_bins[i]) %>%
      dplyr::filter(MinBP < max_ageprev) %>%
      nrow()
    
    if (subset == 0) {
      garb1 <- garb1 %>%
        dplyr::mutate(maxage = ifelse(bins == unique_bins[i], -9999, maxage))
    } else {
      max_agecurrent <- garb1 %>%
        dplyr::ungroup() %>%
        dplyr::filter(bins == unique_bins[i]) %>%
        dplyr::filter(MinBP < max_ageprev) %>%
        dplyr::select(MinBP) %>%
        max(.)
      
      garb1 <- garb1 %>%
        dplyr::mutate(maxage = ifelse(bins == unique_bins[i], max_agecurrent, maxage))
    }
  }
}

# Remove rows (latitude bins) that did not have a year returned (i.e., there were no dates younger than the previous latitude).
garb2 <- garb1 %>%
  dplyr::filter(maxage != -9999)

# Get the unique years for each latitude.
maize_index <- unique(garb2$maxage)

garb3 <- garb2 %>%
  dplyr::filter(MinBP == maxage)

garb3 <- garb3 %>%
  dplyr::mutate(date = paleomat::BPtoBCAD(MinBP))

# now just plot the northern frontier
# progressively younger sites must be farther north than the previous site
# EarlyMaizeNF <- EarlyMaize %>%
#   filter(ID==279 | ID==271 | ID==76 | ID==46 | ID==49 | ID==135 | ID==445
#          | ID==441 | ID==469 | ID==473)

garb3$Elevation_masl <- as.numeric(garb3$Elevation_masl)

# All other points to plot.
allOther <- garb %>%
  filter(!Lab_code %in% garb3$Lab_code) %>%
  dplyr::mutate(date = paleomat::BPtoBCAD(MinBP))

```

```{r maize_frontier_fig, fig.cap="Figure. This graph starts from all the sites with uncontested directly dated maize macrofossils from Mexico and the southwestern US in the Ancient Maize Map database. Beginning at Xihuatoxtla in Guerrero, we sequentially pulled out one site at a time, selecting the next site from an age-sorted list that was both younger in age and farther north than the previous one. So this is the graph of the location of maize’s northern frontier through time. Focus on establishment of maize agriculture, over presence of maize.  Overall this graph reflects the strongly linear relationship of northing and earliest maize. Such a relationship implies the operation of strong constraints on maize’s northern spread.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

# Plot using a linear model.
garb3 %>%
  #arrange(desc(Latitude)) %>%
  dplyr::mutate(State_prov = as.factor(State_prov)) %>%
  ggplot(., aes(x = date, y = Latitude, color = fct_rev(State_prov))) +
  # geom_hline(yintercept = 38.09, colour = "darkgrey") +
  # geom_hline(yintercept = 31.332817, colour = "darkgrey") +
  geom_hline(yintercept = 37.7, colour = "black") +
  geom_hline(yintercept = 37, colour = "black") +
  geom_point(data = allOther, aes(x = date, y = Latitude, color = NULL), colour = "darkgrey", fill = "darkgrey", alpha = 0.45) +
  geom_point(shape = 19, size = 4, aes(color = fct_rev(State_prov))) +
  #  geom_text(label = EarlyMaizeNF$Name, color = 'black', offset = 10) +
  geom_smooth(aes(group = 1),
              method = 'lm',
              se = F,
              linetype = 1) +
  stat_smooth(
    method = loess,
    span = 0.9,
    se = FALSE,
    size = 1.5
  )  +
  #annotate("text", x = -4000, y = 35, label = "Upland United \n States Southwest", size = 7) +
  annotate("text", x = -4000, y = 37.35, label = "Central Mesa Verde", size = 5) +
  ggrepel::geom_label_repel(
    aes(date, Latitude,
        colour = State_prov, label = Site_name),
    max.iter = 4000,
    cex = 6.5,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    # xlim = c (-6500, 0),
    #nudge_y = 3,
    #nudge_x = 50,
    force = 60,
    box.padding = 1
  ) +
  scale_x_continuous(breaks = seq(-7500, 1500, 1000),
                     minor_breaks = seq(-6500, 1500, 1000)) +
  scale_y_continuous(breaks = seq(15, 40, 5),
                     minor_breaks = seq(20, 35, 5),
                     limits = c(15, 40)) +
  xlab("Year BC/AD") +
  ggpubr::color_palette(palette = "jco") +
  theme_bw()  +
  theme(legend.justification = 'left',
        legend.position = c(0.01, 0.82),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size=18, colour="black")) +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  theme(axis.title.x = element_text(size = 24, colour="black"),
        axis.text.x  = element_text(size = 22, colour="black")) +
  theme(axis.title.y = element_text(size = 24, colour="black"),
        axis.text.y  = element_text(size = 22, colour="black"))

ggplot2::ggsave("vignettes/figures/maize_frontier_fig_macrofossils.png", dpi = 600)

# Plot the residuals of the linear model.
# m <- lm(Latitude~date, garb3)
# plot(m)

```


```{r maize_frontier_animation, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}
smooth_vals = predict(lm(Latitude~date,garb3))
garb3$smooth_vals <- smooth_vals


anim <- ggplot(garb3, aes(x = date, y = Latitude, color = State_prov)) +
  geom_point(shape = 1, size = 4, aes(group = seq_along(date))) +
  geom_line(aes(y = smooth_vals), colour = "blue") +
  gganimate::transition_reveal(date) +
  gganimate::ease_aes("linear") +
  #  geom_text(label = EarlyMaizeNF$Name, color = 'black', offset = 10) +
  ggrepel::geom_label_repel(
    aes(date, Latitude,
        colour = State_prov, label = Site_name),
    max.iter = 4000,
    cex = 4
  ) +
  theme_classic()  +
  xlab("Year BC/AD") +
  scale_x_continuous(breaks = seq(-7000, 1000, 1000)) +
  scale_y_continuous(breaks = seq(10, 50, 5)) +
  geom_hline(yintercept = 38.09) +
  geom_hline(yintercept = 31.332817) +
  theme(legend.justification = 'left',
        legend.position = c(0.01, 0.65)) +
  theme(legend.title = element_blank()) +
  theme(legend.direction = "vertical", panel.grid.major = element_line(colour = "light grey")) +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  theme(axis.title.x = element_text(size = 14),
        axis.text.x  = element_text(size = 12)) +
  theme(axis.title.y = element_text(size = 14),
        axis.text.y  = element_text(size = 12))

# anim2 <- gganimate::animate(anim, fps = 10, duration = 8, height = 6, width = 6, units = "in", res = 300)
# gganimate::anim_save(animation = anim2, filename ="/Users/andrew/Dropbox/WSU/SKOPEII/model/Paper 2/Figures/Maize_Frontier_lm.gif")

```


```{r all_maize_sites_fig, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

# Plot all sites
MDB_full_cal_min$Latitude <- as.double(MDB_full_cal_min$Latitude)
MDB_full_cal_min$MinBP <- as.numeric(MDB_full_cal_min$MinBP)
MDB_full_cal_min$MedianBP <- as.numeric(MDB_full_cal_min$MedianBP)

ggplot(MDB_full_cal_min, aes(x=MinBP, y=Latitude, color=State_prov)) +
  theme_gray()  +
  geom_point(shape = 1, size = 4) +
  # scale_x_continuous(n.breaks = 10) +
  # scale_y_continuous(n.breaks = 10) +
  #  geom_text(label = EarlyMaizeNF$Name, color = 'black', offset = 10) +
  geom_smooth(aes(group = 1), method = 'lm', se = F, linetype = 1) +
  stat_smooth(method = loess, span=0.9, se=FALSE, size=1.5)  +
  # geom_label_repel(aes(MinBP, Latitude,
  #                      colour=State_prov, label=Site_name), max.iter=4000, cex= 4) +
  theme(legend.justification = 'left', legend.position=c(0.33,0.8)) +
  theme(legend.title=element_blank()) +
  theme(legend.direction = "horizontal") +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(axis.title.x = element_text(size=10),
        axis.text.x  = element_text(size=12)) +
  theme(axis.title.y = element_text(size=10),
        axis.text.y  = element_text(size=12))

#ggplot2::ggsave("vignettes/figures/all_maize_sites_fig.png", dpi = 600)

```


```{r anomaly_maize_plot, fig.width=8, fig.height=9, echo=FALSE}

# Prepare Maize plot.
MDB_FULL <-
  MDB_full_cal_min %>%
  dplyr::mutate(MinBP = as.numeric(MinBP),
                Latitude = as.numeric(Latitude),
                date = paleomat::BPtoBCAD(MinBP)) %>%
  dplyr::filter(date >= -3000 & date <= 1800) %>%
  dplyr::mutate(date = (DescTools::RoundTo(
    date, multiple = 100, FUN = floor
  ) + 50)) %>%
  dplyr::select(Longitude, Latitude, Lab_code, Site_name, Elevation_masl, date) %>%
  mutate_at(c("Longitude", "Elevation_masl"), ~ as.numeric(as.character(.))) %>%
  dplyr::filter(Latitude >= 31.334 &
                  Latitude <= 38.09 & Longitude < -104.00)

maize_plot <- ggplot(MDB_FULL, aes(x = date, y = Latitude)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red", formula = y ~ x) +
  xlab("Year BC/AD") +
  ylab("Latitude") +
  scale_x_continuous(
    breaks = seq(-3000, 1500, 500)) +
  scale_y_continuous(breaks = seq(31.5, 38, 0.5)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )


# Use faceting to plot together.
t1 <- temp_anom %>% 
  dplyr::select(1:2) %>%
  reshape2::melt(measure.vars = 2) %>% 
  dplyr::mutate(variable = "Anomaly") %>% 
  dplyr::rename(date = 1) %>% 
  dplyr::filter(date >= -3000 & date <= 1600)
t2 <- MDB_FULL %>% 
  dplyr::select(date, Latitude) %>% 
  reshape2::melt(measure.vars = c("Latitude"))
multi.plot <- rbind(t1, t2)

scales_y <- list(
  `Anomaly` = scale_y_continuous(limits = c(-2.5, 0.5), breaks = seq(-2.5, 0.5, 0.25)),
  `Latitude` = scale_y_continuous(limits = c(31.5, 37.5), breaks = seq(31.5, 37.5, 0.5))
)

ggplot(multi.plot, mapping = aes(x = date, y = value)) +
  facet_grid(variable ~ ., scales = "free_y") +
  geom_line(data = t1, stat = "identity") + 
  geom_point(data = t2, stat = "identity") +
  stat_smooth(data = t2, method = "lm", col = "red", formula = y ~ x) +
  xlab("Year BC/AD") +
  ylab("Value") +
  scale_x_continuous(
    breaks = seq(-3000, 1500, 500),
    limits = c(-3000, 1500)
  ) +
  facetscales::facet_grid_sc(rows = vars(variable), 
                             scales = list(y = scales_y)) +
  #scale_y_continuous(breaks = seq(31.5, 38, 0.5)) +
  theme_bw() +
  theme(
    strip.text.y = element_text(size = 12),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )

ggplot2::ggsave("vignettes/figures/anomaly_maize_plot.png", dpi = 600)

```




```{r process_maize_frontier_gdd, message = FALSE, warning = FALSE, results = 'hide'}

# Extract GDD for each location.
# MDB_full_cal <-
#   raster::extract(
#     x =  global_gdd,
#     y = MDB_full_cal %>%
#       dplyr::select(Longitude, Latitude) %>%
#       dplyr::mutate(dplyr::across(everything(), ~ as.numeric(.x))),
#     df = TRUE
#   ) %>%
#   dplyr::select(gdd = 2) %>%
#   dplyr::bind_cols(MDB_full_cal, .)

MDB_full_cal <- ok %>%
  dplyr::filter(Type == "MacroSample") #%>%
#   dplyr::select(-gdd)

# Find minimum 2 sigma for each row.
# Change all text that says "NA to NA" from the rcarbon output to a regular NA.
MDB_full_cal <- MDB_full_cal %>%
  dplyr::mutate_all(function(x) gsub("NA to NA", NA, x))
# subset the dataframe to only have the 2 sigma data and the unique lab code.
df1 <- MDB_full_cal %>% 
  dplyr::select(1, 35:41)
#create an index that shows which cells are and are not NA.
ind <- !is.na(df1)
# Get the last sigma date that is True in each row (/the last non-NA value).
sigma_min <- tapply(df1[ind], row(df1)[ind], tail, 1)
#Bind back to lab_code. Need to fix these 2 lines of code, so that I never lose the unique identifier.
sigma_min <- cbind(df1$Lab_code, sigma_min)
#Update colnames.
colnames(sigma_min) <- c("Lab_code", "MinBP")
#Separating the text in each date box, so that I can extract the minimum year.
sigma_min <- sigma_min %>%
  as.data.frame() %>%
  tidyr::separate(MinBP, into = c("pre", "to", "MinBP")) %>%
  dplyr::select(-pre:-to)

# Add this data back to the large dataframe.
MDB_full_cal_min <- dplyr::left_join(MDB_full_cal, sigma_min, by = "Lab_code")
# Reorder so that the Min years are by medianBP.
MDB_full_cal_min <- MDB_full_cal_min %>% 
  dplyr::relocate(MinBP, .after = MedianBP)


# Reorder the gdd to be in descending order.
garb <- MDB_full_cal_min %>%
  dplyr::arrange(desc(gdd))

# Find index of the oldest date in maize data using the minimum BP year, then remove all rows above that date.
delrows <- which.max(garb$MinBP) - 1
garb <- garb %>%
  dplyr::slice(-1:-delrows)

# Get the actual year and gdd for the oldest maize sample.
starting_maize <- which.max(garb$MinBP)
garb$MinBP <- as.numeric(garb$MinBP)
garb$gdd <- as.double(garb$gdd)
starting_date <- garb[starting_maize, ] %>% .$MinBP
starting_gdd <- garb[starting_maize, ] %>% .$gdd

# Limit just to SW.
garb <- garb %>%
  filter(str_detect(Country, "^Mexico") | str_detect(State_prov, "Arizona|Mexico|Utah|Colorado"))

# Get the minimum gdd in the dataset.
min_gdd <- plyr::round_any(as.double(min(garb$gdd)), 100, f = floor)
max_gdd <- plyr::round_any(as.double(max(garb$gdd)), 100, f = ceiling)

noBins <- (max_gdd - min_gdd)/1

# Create new dataframe that has the northern frontier of maize through time. Pick a site that has fewer GDD than the previous site and is younger.
# LOOP: Set up a loop by first determining how many bins there are. For example, if I do a bin size of 400 GDD, and if the GDD range is from 1500 to 5100, then I would have 9 bins. That would give me how many times I need to loop through. Then, I would find the starting point for the first record, whether that is starting with the absolute oldest date or starting at the greatest GDD with the oldest date. Once I have a starting point, then I want to loop through each bin (e.g., 1500-1900, 1900-2300, etc.) and find the oldest date, but it must be younger than the previous selection.

# Create bins.
# Find cutoffs for the GDD bins in the dataset.
cutOffs <- seq(min_gdd, max_gdd, 1)

# Convert to make sure columns are numeric then create the actual bins (as factors).
garb$bins <- cut(as.numeric(garb$gdd), breaks = cutOffs)
garb$binsNo <- cut(as.numeric(garb$gdd), breaks = cutOffs, labels = FALSE)

#test <- garb %>% group_by(bins) %>% top_n(1, MinBP)
unique_bins <- unique(garb$bins)

garb1 <- garb

for (i in 1:length(unique_bins)){
  
  if (i == 1){
    garb1 <- garb1 %>%
      dplyr::group_by(bins) %>%
      dplyr::mutate(maxage = ifelse(bins == unique_bins[i], max(MinBP), NA))
    
    max_agecurrent <- max(garb1$MinBP)
  } else {
    max_ageprev <- max_agecurrent
    # garb1 %>%
    #   ungroup() %>%
    #   dplyr::filter(bins == unique_bins[i-1]) %>%
    #   dplyr::filter(MinBP < max_ageprev) %>%
    #   dplyr::select(MinBP) %>%
    #   max(.)
    
    subset <- garb1 %>%
      dplyr::ungroup() %>%
      dplyr::filter(bins == unique_bins[i]) %>%
      dplyr::filter(MinBP < max_ageprev) %>%
      nrow()
    
    if (subset == 0) {
      garb1 <- garb1 %>%
        dplyr::mutate(maxage = ifelse(bins == unique_bins[i], -9999, maxage))
    } else {
      max_agecurrent <- garb1 %>%
        dplyr::ungroup() %>%
        dplyr::filter(bins == unique_bins[i]) %>%
        dplyr::filter(MinBP < max_ageprev) %>%
        dplyr::select(MinBP) %>%
        max(.)
      
      garb1 <- garb1 %>%
        dplyr::mutate(maxage = ifelse(bins == unique_bins[i], max_agecurrent, maxage))
    }
  }
}

# Remove rows (GDD bins) that did not have a year returned (i.e., there were no dates younger than the previous GDD).
garb2 <- garb1 %>%
  dplyr::filter(maxage != -9999)

# Get the unique years for each latitude.
maize_index <- unique(garb2$maxage)

garb3 <- garb2 %>%
  dplyr::filter(MinBP == maxage)

garb3 <- garb3 %>%
  dplyr::mutate(date = paleomat::BPtoBCAD(MinBP))

# now just plot the northern frontier
# progressively younger sites must be farther north than the previous site
# EarlyMaizeNF <- EarlyMaize %>%
#   filter(ID==279 | ID==271 | ID==76 | ID==46 | ID==49 | ID==135 | ID==445
#          | ID==441 | ID==469 | ID==473)

garb3$Elevation_masl <- as.numeric(garb3$Elevation_masl)

# All other points to plot.
allOther <- garb %>%
  dplyr::filter(!Lab_code %in% garb3$Lab_code) %>%
  dplyr::mutate(date = paleomat::BPtoBCAD(MinBP),
                date = as.numeric(date),
                Latitude = as.double(Latitude))


```

```{r GDD_temp_slopes}

temp_anom <- readr::read_csv("https://raw.githubusercontent.com/Archaeo-Programmer/paleoMAT/master/vignettes/tables/supp_table_s2.csv") %>% 
  dplyr::select(date = Year, anomaly = 2)

garb3 %>% 
  dplyr::ungroup() %>% 
  dplyr::select(Site_name, State_prov, gdd, date) %>% 
  dplyr::left_join(., temp_anom, by = "date") %>% 
  #dplyr::filter(!is.na(anomaly)) %>% 
  dplyr::mutate(delta_gdd = gdd - lag(gdd),
                delta_anom = anomaly - lag(anomaly)) %>% 
  ggplot(., aes(x = date, y = delta_gdd)) +
  geom_point(shape = 19, size = 4) +
  geom_line(size = 1) +
  geom_smooth(aes(group = 1),
              method = 'lm',
              se = FALSE,
              linetype = 1) +
  ggrepel::geom_label_repel(
    aes(
      label = Site_name),
    max.iter = 4000,
    cex = 6.5,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    force = 60,
    box.padding = 1,
    inherit.aes = TRUE
  ) +
  xlab("Years BC/AD") +
  ylab("\u0394 Annual Accumulated Growing Degree Days") +
  scale_x_continuous(breaks = seq(-1200, 1200, 200),
                     minor_breaks = seq(-1200, 1200, 100),
                     limits = c(-1200, 1300)) +
  scale_y_continuous(breaks = seq(-600, 0, 100),
                     minor_breaks = seq(-600, 0, 50),
                     guide = "axis_minor") +
  theme_bw()+
  theme(
    legend.justification = 'left',
    legend.position = c(0.01, 0.87),
    legend.title = element_blank(),
    legend.direction = "vertical",
    legend.text = element_text(size = 18, colour = "black"), 
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

# ggplot2::ggsave("vignettes/figures/GDD_slopes_overTime.png", dpi = 600)

```

```{r maize_frontier_gdd_fig, fig.cap="Figure.", echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, results = 'hide',fig.keep = 'all', fig.height = 7.73, fig.align = "left"}

# Plot using a linear model.
garb3 %>%
  dplyr::mutate(State_prov = as.factor(State_prov),
                date = as.numeric(date),
                gdd = as.double(gdd)) %>%
  ggplot(., aes(x = date, y = gdd, color = fct_rev(State_prov))) +
  geom_point(data = allOther, aes(x = date, y = gdd, color = NULL), colour = "darkgrey", fill = "darkgrey", alpha = 0.45) +
  geom_point(shape = 19, size = 4, aes(color = fct_rev(State_prov))) +
  geom_smooth(aes(group = 1),
              method = 'lm',
              se = FALSE,
              linetype = 1) +
  # stat_smooth(
  #   method = loess,
  #   span = 0.9,
  #   se = FALSE,
  #   size = 1.5
  # )  +
  ggrepel::geom_label_repel(
    aes(date, gdd,
        colour = State_prov, label = Site_name),
    max.iter = 4000,
    cex = 6.5,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    # xlim = c (-6500, 0),
    #nudge_y = 3,
    #nudge_x = 50,
    force = 60,
    box.padding = 1
  ) +
  scale_x_continuous(breaks = seq(-4500, 1500, 1000),
                     minor_breaks = seq(-4500, 1500, 1000),
                     limits = c(-4500, 1800)) +
  scale_y_continuous(trans = "reverse",
                     breaks = seq(1000, 4000, 500),
                     limits = c(4000, 1000),
                     minor_breaks = seq(1000, 4000, 250),
                     guide = "axis_minor") +
  xlab("Years BC/AD") +
  ylab("Annual Accumulated Growing Degree Days") +
  ggpubr::color_palette(palette = "jco") +
  theme_bw()  +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  theme(
    legend.justification = 'left',
    legend.position = c(0.01, 0.87),
    legend.title = element_blank(),
    legend.direction = "vertical",
    legend.text = element_text(size = 18, colour = "black"), 
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggplot2::ggsave("vignettes/figures/maize_frontier_gdd_fig_macrofossils_smallerbins.png", dpi = 600)

# Plot the residuals of the linear model.
# m <- lm(Latitude~date, garb3)
# plot(m)



# Using Wisconsin Data
# Plot using a linear model.
garb3 %>%
  dplyr::mutate(State_prov = as.factor(State_prov),
                date = as.numeric(date),
                gdd = as.double(gdd)) %>%
  ggplot(., aes(x = date, y = gdd, color = fct_rev(State_prov))) +
  geom_point(data = allOther, aes(x = date, y = gdd, color = NULL), colour = "darkgrey", fill = "darkgrey", alpha = 0.45) +
  geom_point(shape = 19, size = 4, aes(color = fct_rev(State_prov))) +
  geom_smooth(aes(group = 1),
              method = 'lm',
              se = FALSE,
              linetype = 1) +
  # stat_smooth(
  #   method = loess,
  #   span = 0.9,
  #   se = FALSE,
  #   size = 1.5
  # )  +
  ggrepel::geom_label_repel(
    aes(date, gdd,
        colour = State_prov, label = Site_name),
    max.iter = 4000,
    cex = 6.5,
    show.legend  = F,
    min.segment.length = unit(0, 'lines'),
    # xlim = c (-6500, 0),
    #nudge_y = 3,
    #nudge_x = 50,
    force = 60,
    box.padding = 1
  ) +
  scale_x_continuous(breaks = seq(-7500, 1500, 1000),
                     minor_breaks = seq(-6500, 1500, 1000)) +
  scale_y_continuous(trans = "reverse",
                     breaks = seq(1500, 5000, 500),
                     limits = c(5200, 1500),
                     minor_breaks = seq(1500, 5000, 250),
                     guide = "axis_minor") +
  xlab("Years BC/AD") +
  ylab("Annual Accumulated Growing Degree Days") +
  ggpubr::color_palette(palette = "jco") +
  theme_bw()  +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  theme(
    legend.justification = 'left',
    legend.position = c(0.01, 0.87),
    legend.title = element_blank(),
    legend.direction = "vertical",
    legend.text = element_text(size = 18, colour = "black"),
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

ggplot2::ggsave("vignettes/figures/maize_frontier_gdd_fig_macrofossils_smallerbins_wisconsindata.png", dpi = 600)

```






```{r paleocar}

#paleocar <- raster::brick("/Users/andrew/Dropbox/WSU/SKOPEII/model/paleocar_GDD_MAT_extent.tif")
paleocar <- raster::brick("/Users/andrew/Dropbox/WSU/SKOPEII/model/paleocar_GDD_Full_Dataset.tif")

x.stats <- data.frame(x.mean=raster::cellStats(paleocar, "mean"))
x.stats2 <- x.stats %>% 
  dplyr::mutate(year = row_number()) %>% 
  `rownames<-`(seq_len(nrow(.))) %>% 
  dplyr::rename(anom = 1)

temp_anom <- readr::read_csv("https://raw.githubusercontent.com/Archaeo-Programmer/paleoMAT/master/vignettes/tables/supp_table_s2.csv") %>% 
  dplyr::rename(year = 1, anom = 2, ci = 3, se = 4)

# For our reconstruction, we first extract the fitted values from the loess line, as plotting above.
p <- paleocar_paleomat_sites2 %>%
  ggplot2::qplot(year, anom, data = .) +
  ggplot2::stat_smooth(
    method = "loess",
    formula = y ~ x,
    aes(outfit = fit <<-
          ..y..),
    span = 0.10,
    n = 2000
  )

paleocar_loess <- ggplot2::ggplot_build(p)$data[[2]]

p <- readr::read_rds("/Users/andrew/Dropbox/WSU/SKOPEII/model/paleomat/vignettes/data/diagnostics_reconstruction/final_paleomat_dataset3.rds") %>%
  dplyr::filter(date >= -3000) %>%
  ggplot2::qplot(date, anom_bootstrap, data = .) +
  ggplot2::stat_smooth(
    method = "loess",
    formula = y ~ x,
    aes(outfit = fit <<-
          ..y..),
    span = 0.05,
    n = 5000
  )

anom_loess4 <- ggplot2::ggplot_build(p)$data[[2]]

temp_anom_standard <- anom_loess4 %>%
  dplyr::filter(x >= 1 & x <= 2000) %>%
  dplyr::mutate(Series = "Gillreath-Brown") %>%
  dplyr::select(year = x, anom = y, Series)

paleocar_standard <- paleocar_loess %>%
  dplyr::mutate(Series = "Bocinsky") %>%
  dplyr::select(year = x, anom = y, Series)

paleocar_paleomat <-
  dplyr::bind_rows(temp_anom_standard, paleocar_standard)

# paleocar and paleomat
paleocar_paleomat %>%
  dplyr::group_by(Series) %>%
  dplyr::mutate(update = (anom - mean(anom)) / sd(anom)) %>%
  ggplot2::ggplot(aes(x = year, y = update, colour = Series)) +
  geom_hline(
    yintercept = 0,
    color = "darkgrey",
    lty = 2,
    lwd = 1.25
  ) +
  geom_line(size = 2.0) +
  scale_color_manual(values = c("#A60F2D", "cornflowerblue")) +
  xlab("Years AD") +
  ylab("Standardized Temperature Values (Z-Scores)") +
  scale_x_continuous(
    limits = c(0, 2000),
    breaks = seq(0, 2000, 200),
    minor_breaks = seq(0, 2000, by = 100),
    guide = "axis_minor"
  ) +
  scale_y_continuous(breaks = seq(-2, 3, 0.5)) +
  theme_bw() +
  theme(
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    ),
    legend.text = element_text(size = 19, family = "Helvetica"),
    legend.title = element_blank()
  )


x.stats2 %>%
  ggplot2::ggplot(aes(x = year, y = `x.mean`)) +
  #geom_line(size = 2, colour = "cornflowerblue") +
  geom_smooth(
    method = "loess",
    span = 0.15,
    aes(x = year),
    size = 2,
    colour = "cornflowerblue"
  ) +
  scale_x_continuous(
    limits = c(0, 2000),
    breaks = seq(0, 2000, 500),
    minor_breaks = seq(0, 2000, by = 100),
    guide = "axis_minor"
  ) +
  # scale_y_continuous(
  #   limits = c(-2.5, 2.5),
  #   breaks = seq(-2.5, 2.5, 0.5),
  #   minor_breaks = seq(-2.5, 2.5, by = 0.25),
  #   guide = "axis_minor"
  # ) +
  theme_bw() +
  xlab("Years BC/AD") +
  ylab("Temperature Anomaly (°C)") +
  theme(
    axis.ticks.length = unit(0.125, "inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )




paleomat_sites <- readr::read_rds("/Users/andrew/Dropbox/WSU/SKOPEII/model/paleomat/vignettes/data/diagnostics_reconstruction/final_paleomat_dataset3.rds") %>% 
  dplyr::group_by(site.name) %>% 
  dplyr::slice(1) %>% 
  dplyr::select(long, lat) %>% 
  sf::st_as_sf(coords = c("long", "lat"), crs = 4326)

paleocar_paleomat_sites <- raster::extract(paleocar, paleomat_sites, df = TRUE)

paleocar_paleomat_sites2 <- paleocar_paleomat_sites %>% 
  dplyr::select(-ID) %>% 
  dplyr::filter(!is.na(`paleocar_GDD_MAT_extent.1`)) %>% 
  stack() %>% 
  dplyr::mutate(ind = as.numeric(gsub("\\D+", "", ind))) %>% 
  dplyr::group_by(ind) %>% 
  dplyr::summarise(values = mean(values)) %>% 
  dplyr::rename(year = 1, anom = 2)


```


























```{r}

library(plotly)

plot_ly(
  x = MDB_full_cal_min$Longitude ,
  y = MDB_full_cal_min$Latitude,
  z = MDB_full_cal_min$date,
  type = "scatter3d",
  mode = "markers",
       marker = list(color = MDB_full_cal_min$gdd,
                     # Use either a named palette in the above list:
                     #colorscale = 'Greys',
                     # Or use a list of vector scales.
                     colorscale = list(c(0, 1), c("blue", "red")),
                     showscale = TRUE)) %>%
  layout(scene = list(xaxis = list(range = c(-105, -111)), 
                      yaxis = list(range = c(39, 32)),
                      zaxis=list(range = c(-2500,1500))))


```
